"""Learning-first KRK autogrowth utilities."""

from .arbitration import (
    LocalArbitrationConfig,
    LocalArbitrationMetrics,
    LocalArbitrationResult,
    arbitrate_local_action,
    build_local_action_nodes,
    evaluate_local_arbitration_arm,
    run_local_arbitration_experiment,
)
from .candidate_generation import (
    CONTEXT_SPECIALIZED_FEATURES,
    ContextSpecializedCandidateConfig,
    ContextSpecializedCandidateResult,
    RiskAwareCandidateConfig,
    RiskAwareCandidateResult,
    generate_context_specialized_candidates,
    generate_risk_aware_candidates,
    run_context_specialized_candidate_experiment,
    run_risk_aware_candidate_experiment,
)
from .evaluate import (
    ArmMetrics,
    EvaluationConfig,
    EvaluationResult,
    evaluate_arm,
    evaluate_baseline_and_sham,
)
from .experiment import (
    AutogrowthExperimentConfig,
    AutogrowthExperimentResult,
    run_autogrowth_experiment,
)
from .features import (
    FORBIDDEN_LEARNER_TERMS,
    extract_learner_features,
    make_trace_record,
    validate_learner_record,
)
from .fragment_chain_curriculum import (
    FragmentChainCurriculumConfig,
    FragmentChainCurriculumResult,
    evaluate_fragment_chain_arm,
    run_fragment_chain_curriculum,
)
from .mining import (
    CandidateMiningConfig,
    CandidateMiningResult,
    mine_triplet_candidates_from_artifact,
    mine_triplet_candidates_from_records,
)
from .positions import (
    KRKPositionSet,
    can_mate_in_one,
    generate_position_sets,
    is_valid_krk_seed,
)
from .script_candidates import (
    LocalScriptConfig,
    LocalScriptMetrics,
    LocalScriptResult,
    choose_local_script_action,
    generate_local_script_candidates,
    run_local_script_experiment,
)
from .script_fragments import (
    ScriptFragmentConfig,
    ScriptFragmentResult,
    generalize_script_candidates_to_fragments,
    run_script_fragment_experiment,
)
from .sandbox import (
    SandboxConfig,
    SandboxMetrics,
    SandboxResult,
    evaluate_candidate_sandbox,
    evaluate_sandbox_arm,
    load_selected_candidate,
)
from .suppressor import (
    LocalSuppressorConfig,
    LocalSuppressorMetrics,
    LocalSuppressorResult,
    derive_local_suppressor,
    evaluate_local_suppressor_arm,
    run_local_suppressor_experiment,
    suppressor_confirms,
)
from .traces import (
    TraceCollectionConfig,
    TraceCollectionResult,
    collect_trace_records,
)
from .training import (
    CandidateLifecycle,
    GrowthTrainingConfig,
    GrowthTrainingResult,
    load_candidate_pool,
    train_growth_candidates,
)
from .topological_growth import (
    TopologicalGrowthRunwayConfig,
    TopologicalGrowthRunwayResult,
    build_triplet_chain_view,
    inventory_legacy_predefined_topology_runs,
    run_topological_growth_runway,
)

__all__ = [
    "ArmMetrics",
    "AutogrowthExperimentConfig",
    "AutogrowthExperimentResult",
    "CandidateMiningConfig",
    "CandidateMiningResult",
    "CONTEXT_SPECIALIZED_FEATURES",
    "EvaluationConfig",
    "EvaluationResult",
    "FORBIDDEN_LEARNER_TERMS",
    "FragmentChainCurriculumConfig",
    "FragmentChainCurriculumResult",
    "CandidateLifecycle",
    "GrowthTrainingConfig",
    "GrowthTrainingResult",
    "KRKPositionSet",
    "LocalArbitrationConfig",
    "LocalArbitrationMetrics",
    "LocalArbitrationResult",
    "LocalScriptConfig",
    "LocalScriptMetrics",
    "LocalScriptResult",
    "LocalSuppressorConfig",
    "LocalSuppressorMetrics",
    "LocalSuppressorResult",
    "ContextSpecializedCandidateConfig",
    "ContextSpecializedCandidateResult",
    "RiskAwareCandidateConfig",
    "RiskAwareCandidateResult",
    "SandboxConfig",
    "SandboxMetrics",
    "SandboxResult",
    "ScriptFragmentConfig",
    "ScriptFragmentResult",
    "TraceCollectionConfig",
    "TraceCollectionResult",
    "TopologicalGrowthRunwayConfig",
    "TopologicalGrowthRunwayResult",
    "arbitrate_local_action",
    "build_local_action_nodes",
    "build_triplet_chain_view",
    "can_mate_in_one",
    "collect_trace_records",
    "evaluate_arm",
    "evaluate_baseline_and_sham",
    "evaluate_candidate_sandbox",
    "evaluate_fragment_chain_arm",
    "evaluate_local_arbitration_arm",
    "evaluate_local_suppressor_arm",
    "evaluate_sandbox_arm",
    "extract_learner_features",
    "generate_context_specialized_candidates",
    "generate_local_script_candidates",
    "generalize_script_candidates_to_fragments",
    "generate_risk_aware_candidates",
    "generate_position_sets",
    "is_valid_krk_seed",
    "inventory_legacy_predefined_topology_runs",
    "load_selected_candidate",
    "load_candidate_pool",
    "make_trace_record",
    "mine_triplet_candidates_from_artifact",
    "mine_triplet_candidates_from_records",
    "derive_local_suppressor",
    "run_autogrowth_experiment",
    "run_local_arbitration_experiment",
    "run_local_script_experiment",
    "run_local_suppressor_experiment",
    "run_script_fragment_experiment",
    "run_topological_growth_runway",
    "run_context_specialized_candidate_experiment",
    "run_fragment_chain_curriculum",
    "run_risk_aware_candidate_experiment",
    "suppressor_confirms",
    "choose_local_script_action",
    "train_growth_candidates",
    "validate_learner_record",
]
