"""Learning-first KRK autogrowth utilities."""

from .arbitration import (
    LocalArbitrationConfig,
    LocalArbitrationMetrics,
    LocalArbitrationResult,
    arbitrate_local_action,
    build_local_action_nodes,
    evaluate_local_arbitration_arm,
    run_local_arbitration_experiment,
)
from .candidate_generation import (
    CONTEXT_SPECIALIZED_FEATURES,
    ContextSpecializedCandidateConfig,
    ContextSpecializedCandidateResult,
    RiskAwareCandidateConfig,
    RiskAwareCandidateResult,
    generate_context_specialized_candidates,
    generate_risk_aware_candidates,
    run_context_specialized_candidate_experiment,
    run_risk_aware_candidate_experiment,
)
from .continuation_retry import (
    ContinuationRetryConfig,
    ContinuationRetryMetrics,
    ContinuationRetryResult,
    choose_continuation_retry_action,
    evaluate_continuation_retry_arm,
    run_continuation_retry_experiment,
)
from .curriculum_reward_recovery import (
    CurriculumRewardRecoveryConfig,
    CurriculumRewardRecoveryResult,
    run_curriculum_reward_recovery,
    score_non_terminal_progress,
)
from .evaluate import (
    ArmMetrics,
    EvaluationConfig,
    EvaluationResult,
    evaluate_arm,
    evaluate_baseline_and_sham,
)
from .fence_boundary_rehearsal import (
    FenceBoundaryRehearsalConfig,
    FenceBoundaryRehearsalResult,
    run_fence_boundary_rehearsal,
)
from .fence_boundary_signal import (
    FenceBoundarySignalConfig,
    FenceBoundarySignalResult,
    run_fence_boundary_signal,
)
from .edge_fence_curriculum import (
    EdgeFenceCurriculumConfig,
    EdgeFenceCurriculumResult,
    run_edge_fence_curriculum,
)
from .foundation_curriculum import (
    ActionRanker,
    FoundationCurriculumConfig,
    FoundationCurriculumResult,
    run_foundation_curriculum,
)
from .handoff_filter_validation import (
    HandoffFilterValidationConfig,
    HandoffFilterValidationResult,
    run_handoff_filter_validation,
)
from .experiment import (
    AutogrowthExperimentConfig,
    AutogrowthExperimentResult,
    run_autogrowth_experiment,
)
from .features import (
    FORBIDDEN_LEARNER_TERMS,
    extract_learner_features,
    make_trace_record,
    validate_learner_record,
)
from .fragment_chain_curriculum import (
    FragmentChainCurriculumConfig,
    FragmentChainCurriculumResult,
    evaluate_fragment_chain_arm,
    run_fragment_chain_curriculum,
)
from .lag_terminals import (
    LagFragmentChainMetrics,
    LagTerminalConfig,
    LagTerminalResult,
    choose_lag_fragment_chain_action,
    evaluate_lag_fragment_chain_arm,
    evaluate_lag_terminal,
    run_lag_terminal_experiment,
)
from .mining import (
    CandidateMiningConfig,
    CandidateMiningResult,
    mine_triplet_candidates_from_artifact,
    mine_triplet_candidates_from_records,
)
from .positions import (
    KRKPositionSet,
    can_mate_in_one,
    generate_position_sets,
    is_valid_krk_seed,
)
from .precision_gate import (
    LocalPrecisionGate,
    PrecisionGateConfig,
    PrecisionGateResult,
    audit_confinement_sign_semantics,
    derive_local_precision_gate,
    run_precision_gate_experiment,
)
from .persisted_pool_validation import (
    PersistedPoolValidationConfig,
    PersistedPoolValidationResult,
    run_persisted_pool_validation,
)
from .retry_edges import (
    RetryEdgeConfig,
    RetryEdgeResult,
    run_retry_edge_experiment,
)
from .retry_diagnostics import (
    RetryDiagnosticsConfig,
    RetryDiagnosticsResult,
    run_retry_diagnostics,
)
from .retry_candidate_expansion import (
    RetryCandidateExpansionConfig,
    RetryCandidateExpansionResult,
    mine_retry_expansion_candidates,
    run_retry_candidate_expansion,
)
from .script_candidates import (
    LocalScriptConfig,
    LocalScriptMetrics,
    LocalScriptResult,
    choose_local_script_action,
    generate_local_script_candidates,
    run_local_script_experiment,
)
from .script_fragments import (
    ScriptFragmentConfig,
    ScriptFragmentResult,
    generalize_script_candidates_to_fragments,
    run_script_fragment_experiment,
)
from .sandbox import (
    SandboxConfig,
    SandboxMetrics,
    SandboxResult,
    evaluate_candidate_sandbox,
    evaluate_sandbox_arm,
    load_selected_candidate,
)
from .suppressor import (
    LocalSuppressorConfig,
    LocalSuppressorMetrics,
    LocalSuppressorResult,
    derive_local_suppressor,
    evaluate_local_suppressor_arm,
    run_local_suppressor_experiment,
    suppressor_confirms,
)
from .terminal_substrate import (
    TerminalFoundationBundle,
    TerminalAffordanceLearner,
    TerminalSubstrateConfig,
    TerminalSubstrateResult,
    action_ranker_behavior_audit,
    extract_terminal_feature_vector,
    feature_substrate_coverage_sample,
    run_terminal_substrate_revival,
    terminal_action_feature_keys,
    train_terminal_foundation_bundle,
)
from .terminal_edge_fence_validation import (
    TerminalEdgeFenceValidationConfig,
    TerminalEdgeFenceValidationResult,
    run_terminal_edge_fence_validation,
)
from .traces import (
    TraceCollectionConfig,
    TraceCollectionResult,
    collect_trace_records,
)
from .training import (
    CandidateLifecycle,
    GrowthTrainingConfig,
    GrowthTrainingResult,
    load_candidate_pool,
    train_growth_candidates,
)
from .topological_growth import (
    TopologicalGrowthRunwayConfig,
    TopologicalGrowthRunwayResult,
    build_triplet_chain_view,
    inventory_legacy_predefined_topology_runs,
    run_topological_growth_runway,
)

__all__ = [
    "ArmMetrics",
    "AutogrowthExperimentConfig",
    "AutogrowthExperimentResult",
    "CandidateMiningConfig",
    "CandidateMiningResult",
    "CONTEXT_SPECIALIZED_FEATURES",
    "ContinuationRetryConfig",
    "ContinuationRetryMetrics",
    "ContinuationRetryResult",
    "CurriculumRewardRecoveryConfig",
    "CurriculumRewardRecoveryResult",
    "EvaluationConfig",
    "EvaluationResult",
    "EdgeFenceCurriculumConfig",
    "EdgeFenceCurriculumResult",
    "FenceBoundaryRehearsalConfig",
    "FenceBoundaryRehearsalResult",
    "FenceBoundarySignalConfig",
    "FenceBoundarySignalResult",
    "FORBIDDEN_LEARNER_TERMS",
    "ActionRanker",
    "FoundationCurriculumConfig",
    "FoundationCurriculumResult",
    "FragmentChainCurriculumConfig",
    "FragmentChainCurriculumResult",
    "LagFragmentChainMetrics",
    "LagTerminalConfig",
    "LagTerminalResult",
    "CandidateLifecycle",
    "GrowthTrainingConfig",
    "GrowthTrainingResult",
    "HandoffFilterValidationConfig",
    "HandoffFilterValidationResult",
    "KRKPositionSet",
    "LocalArbitrationConfig",
    "LocalArbitrationMetrics",
    "LocalArbitrationResult",
    "LocalScriptConfig",
    "LocalScriptMetrics",
    "LocalScriptResult",
    "LocalSuppressorConfig",
    "LocalSuppressorMetrics",
    "LocalSuppressorResult",
    "LocalPrecisionGate",
    "PrecisionGateConfig",
    "PrecisionGateResult",
    "PersistedPoolValidationConfig",
    "PersistedPoolValidationResult",
    "ContextSpecializedCandidateConfig",
    "ContextSpecializedCandidateResult",
    "RiskAwareCandidateConfig",
    "RiskAwareCandidateResult",
    "RetryEdgeConfig",
    "RetryEdgeResult",
    "RetryDiagnosticsConfig",
    "RetryDiagnosticsResult",
    "RetryCandidateExpansionConfig",
    "RetryCandidateExpansionResult",
    "SandboxConfig",
    "SandboxMetrics",
    "SandboxResult",
    "ScriptFragmentConfig",
    "ScriptFragmentResult",
    "TerminalEdgeFenceValidationConfig",
    "TerminalEdgeFenceValidationResult",
    "TerminalFoundationBundle",
    "TerminalAffordanceLearner",
    "TerminalSubstrateConfig",
    "TerminalSubstrateResult",
    "TraceCollectionConfig",
    "TraceCollectionResult",
    "TopologicalGrowthRunwayConfig",
    "TopologicalGrowthRunwayResult",
    "arbitrate_local_action",
    "build_local_action_nodes",
    "build_triplet_chain_view",
    "can_mate_in_one",
    "collect_trace_records",
    "evaluate_arm",
    "evaluate_baseline_and_sham",
    "evaluate_candidate_sandbox",
    "evaluate_fragment_chain_arm",
    "evaluate_lag_fragment_chain_arm",
    "evaluate_continuation_retry_arm",
    "evaluate_lag_terminal",
    "evaluate_local_arbitration_arm",
    "evaluate_local_suppressor_arm",
    "evaluate_sandbox_arm",
    "extract_learner_features",
    "generate_context_specialized_candidates",
    "generate_local_script_candidates",
    "generalize_script_candidates_to_fragments",
    "generate_risk_aware_candidates",
    "generate_position_sets",
    "is_valid_krk_seed",
    "inventory_legacy_predefined_topology_runs",
    "load_selected_candidate",
    "load_candidate_pool",
    "make_trace_record",
    "mine_triplet_candidates_from_artifact",
    "mine_triplet_candidates_from_records",
    "derive_local_suppressor",
    "run_autogrowth_experiment",
    "run_local_arbitration_experiment",
    "run_local_script_experiment",
    "run_local_suppressor_experiment",
    "run_script_fragment_experiment",
    "run_topological_growth_runway",
    "run_context_specialized_candidate_experiment",
    "run_continuation_retry_experiment",
    "run_curriculum_reward_recovery",
    "run_edge_fence_curriculum",
    "run_fence_boundary_rehearsal",
    "run_fence_boundary_signal",
    "run_fragment_chain_curriculum",
    "run_foundation_curriculum",
    "run_handoff_filter_validation",
    "run_lag_terminal_experiment",
    "run_risk_aware_candidate_experiment",
    "run_retry_edge_experiment",
    "run_retry_diagnostics",
    "run_retry_candidate_expansion",
    "run_precision_gate_experiment",
    "run_persisted_pool_validation",
    "mine_retry_expansion_candidates",
    "derive_local_precision_gate",
    "audit_confinement_sign_semantics",
    "action_ranker_behavior_audit",
    "suppressor_confirms",
    "choose_local_script_action",
    "choose_lag_fragment_chain_action",
    "choose_continuation_retry_action",
    "extract_terminal_feature_vector",
    "feature_substrate_coverage_sample",
    "score_non_terminal_progress",
    "run_terminal_substrate_revival",
    "run_terminal_edge_fence_validation",
    "terminal_action_feature_keys",
    "train_growth_candidates",
    "train_terminal_foundation_bundle",
    "validate_learner_record",
]
